d = {'A' : 'T', 'T' : 'A', 'G' : 'C', 'C' : 'G'}


def get_pal(s):
    ans = ''
    l = len(s)
    for i in range(l):
        ans += d[s[l-1-i]]
    return ans

s = 'GCGCGAACAATTCGTATGTCTTGTAAAGCGAAATGCCCGGCACTAATATCTCCTGTGATATACACTCCCCAGTCTCACCCAGGTGTAGAGGATGAGGAAAGAATTATTGTGCCGCCGTAACAGATATCCCTATGGGGATACTTTTGTACCAGGGCTAACTGGAAGGGATACCGAGTTGAAGCATCGTGCTGTTGACGCGTAGGTTAGAGGCTAATGCAGTCTGCATCAAAACAAACCACACGCACCCAGTTTGTTTCACGATGTACCGTAGCTCTATCCCTGTGTCAGAGCATATAGAACAATTCGCGAGCTTCATGGTACAAAGCGATAGTTATAACTCAAAGAATACGAGCTGTTTCCGCTGACGCCGCACAAAACTAGGCTCGGCCCGCGAGACCGGTAATCTTGCCTCAAGTACCGCTTAGCAGAGGCCCTGGAAGTATGGCACACTTAAGTGTAGAGCCGTTCCTTATCTGTGTGCCATTATGCCAAATGGATGTAAGTATCATAGAACCTTTCCCGTATCACCCTAAGTTACCTGGTTTTTCTGATACACTAACTCAGTTGGCTCTTGTCGAGCAGTGTCATAGTGTGGTCGAAAAGCAGGCCTCGTTACAAGGTAGGGGGTTAACGTGAAAGAACCGGGTCTTAAGCAACAGGACCAAAGGGAGGGTCATGGTCCAAACATTTGTCTCACGGCCATAAGGTTTTCGGGTGTTCCAAGACAAGACTTACCTACTACCCGGTTTCGTGCTATGGCCCCGCTGCTCCGCGAGTCAGTGGATTCATACCCTCCTATATAACATGCTCGCTCGGGGATTTTCACACTCCCTCACGATACGAGAGCAACGTTGCCCGCTTTCTGTTTACACAACTTTCGGCTGGTCGAGGTACGAGTCGGCGC'
l = len(s)

for i in range(l):
    for j in range(l):
        ll = j - i + 1
        if ((ll>3) and (ll<13)):
            usu = s[i:j+1]
            pal = get_pal(usu)
            if usu == pal:
                print(i+1, ll)
